import cv2
import numpy as np

class CameraAdjuster:
    def __init__(self, camera_index=0):
        # Camera settings (adjust these values)
        self.camera_index = camera_index  # 0 for default camera
        self.zoom_factor = 1.0
        self.pan_offset_x = 0
        self.pan_offset_y = 0
        self.brightness = 50
        self.contrast = 50
        self.saturation = 50
        self.exposure = 0
        
        # ROI for face detection area (for positioning reference)
        self.roi_width = 300
        self.roi_height = 300
        
        self.cap = None
        self.running = True
        
    def initialize_camera(self):
        """Initialize camera with OpenCV"""
        self.cap = cv2.VideoCapture(self.camera_index)
        
        # For Raspberry Pi Camera Module v2/v3 (IMX sensor)
        if self.camera_index == 0:  # Usually the Pi camera
            # Try to set camera properties for better quality
            self.cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
            self.cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)
            self.cap.set(cv2.CAP_PROP_FPS, 30)
        
        # Set initial camera parameters
        self.cap.set(cv2.CAP_PROP_BRIGHTNESS, self.brightness / 100.0)
        self.cap.set(cv2.CAP_PROP_CONTRAST, self.contrast / 100.0)
        self.cap.set(cv2.CAP_PROP_SATURATION, self.saturation / 100.0)
        
        return self.cap.isOpened()
    
    def apply_zoom_and_pan(self, frame):
        """Apply zoom and pan transformations"""
        h, w = frame.shape[:2]
        
        # Calculate zoomed dimensions
        new_w = int(w / self.zoom_factor)
        new_h = int(h / self.zoom_factor)
        
        # Calculate center point with pan offset
        center_x = w // 2 + self.pan_offset_x
        center_y = h // 2 + self.pan_offset_y
        
        # Calculate ROI bounds
        x1 = max(0, center_x - new_w // 2)
        y1 = max(0, center_y - new_h // 2)
        x2 = min(w, center_x + new_w // 2)
        y2 = min(h, center_y + new_h // 2)
        
        # Extract ROI
        roi = frame[y1:y2, x1:x2]
        
        # Resize back to original size
        if roi.size > 0:
            frame = cv2.resize(roi, (w, h), interpolation=cv2.INTER_LINEAR)
        
        return frame
    
    def draw_reference_grid(self, frame):
        """Draw reference grid and face detection area"""
        h, w = frame.shape[:2]
        
        # Draw center crosshair
        cv2.line(frame, (w//2, 0), (w//2, h), (0, 255, 0), 1)
        cv2.line(frame, (0, h//2), (w, h//2), (0, 255, 0), 1)
        
        # Draw face detection ROI (optimal area)
        roi_x = w//2 - self.roi_width//2
        roi_y = h//2 - self.roi_height//2
        cv2.rectangle(frame, 
                     (roi_x, roi_y), 
                     (roi_x + self.roi_width, roi_y + self.roi_height), 
                     (0, 255, 0), 2)
        
        # Draw golden ratio lines (for positioning)
        for i in range(1, 3):
            x = int(w * i / 3)
            y = int(h * i / 3)
            cv2.line(frame, (x, 0), (x, h), (255, 255, 0), 1)
            cv2.line(frame, (0, y), (w, y), (255, 255, 0), 1)
        
        return frame
    
    def display_settings(self, frame):
        """Display current settings on screen"""
        settings = [
            f"Zoom: {self.zoom_factor:.2f}x",
            f"Pan X: {self.pan_offset_x}",
            f"Pan Y: {self.pan_offset_y}",
            f"Brightness: {self.brightness}",
            f"Contrast: {self.contrast}",
            f"Saturation: {self.saturation}",
            f"ROI: {self.roi_width}x{self.roi_height}",
            "",
            "CONTROLS:",
            "Z/X: Zoom +/-",
            "Arrow Keys: Pan",
            "B/N: Brightness +/-",
            "C/V: Contrast +/-",
            "S/A: Saturation +/-",
            "R/F: ROI Width +/-",
            "T/G: ROI Height +/-",
            "E: Export Settings",
            "Q: Quit"
        ]
        
        y_offset = 30
        for i, text in enumerate(settings):
            cv2.putText(frame, text, (10, y_offset + i*25), 
                       cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)
        
        return frame
    
    def export_settings(self):
        """Export settings to a Python config file"""
        config = f'''# Camera Configuration - Generated by CameraAdjuster.py
CAMERA_CONFIG = {{
    'zoom_factor': {self.zoom_factor},
    'pan_offset_x': {self.pan_offset_x},
    'pan_offset_y': {self.pan_offset_y},
    'brightness': {self.brightness},
    'contrast': {self.contrast},
    'saturation': {self.saturation},
    'roi_width': {self.roi_width},
    'roi_height': {self.roi_height},
    'exposure': {self.exposure}
}}

# For OpenCV camera setup
def setup_camera(cap):
    cap.set(cv2.CAP_PROP_BRIGHTNESS, CAMERA_CONFIG['brightness'] / 100.0)
    cap.set(cv2.CAP_PROP_CONTRAST, CAMERA_CONFIG['contrast'] / 100.0)
    cap.set(cv2.CAP_PROP_SATURATION, CAMERA_CONFIG['saturation'] / 100.0)
    # For exposure (if supported):
    # cap.set(cv2.CAP_PROP_EXPOSURE, CAMERA_CONFIG['exposure'])
    
    return cap
'''
        
        with open('camera_config.py', 'w') as f:
            f.write(config)
        
        print("Settings exported to camera_config.py")
        print("You can import this in your face detection code:")
        print("from camera_config import CAMERA_CONFIG, setup_camera")
    
    def run(self):
        """Main adjustment loop"""
        if not self.initialize_camera():
            print("Error: Could not open camera")
            return
        
        print("Starting camera adjustment...")
        print("Adjust settings and position camera until face area is properly framed")
        
        while self.running:
            ret, frame = self.cap.read()
            if not ret:
                print("Error: Failed to grab frame")
                break
            
            # Apply transformations
            frame = self.apply_zoom_and_pan(frame)
            
            # Draw reference overlays
            frame = self.draw_reference_grid(frame)
            frame = self.display_settings(frame)
            
            # Show frame
            cv2.imshow('Camera Adjustment - Position & Configure', frame)
            
            # Handle keyboard input
            key = cv2.waitKey(1) & 0xFF
            
            if key == ord('q'):
                break
            elif key == ord('z'):  # Zoom in
                self.zoom_factor = min(5.0, self.zoom_factor + 0.1)
                print(f"Zoom: {self.zoom_factor:.2f}x")
            elif key == ord('x'):  # Zoom out
                self.zoom_factor = max(1.0, self.zoom_factor - 0.1)
                print(f"Zoom: {self.zoom_factor:.2f}x")
            elif key == ord('b'):  # Brightness up
                self.brightness = min(100, self.brightness + 5)
                self.cap.set(cv2.CAP_PROP_BRIGHTNESS, self.brightness / 100.0)
                print(f"Brightness: {self.brightness}")
            elif key == ord('n'):  # Brightness down
                self.brightness = max(0, self.brightness - 5)
                self.cap.set(cv2.CAP_PROP_BRIGHTNESS, self.brightness / 100.0)
                print(f"Brightness: {self.brightness}")
            elif key == ord('c'):  # Contrast up
                self.contrast = min(100, self.contrast + 5)
                self.cap.set(cv2.CAP_PROP_CONTRAST, self.contrast / 100.0)
                print(f"Contrast: {self.contrast}")
            elif key == ord('v'):  # Contrast down
                self.contrast = max(0, self.contrast - 5)
                self.cap.set(cv2.CAP_PROP_CONTRAST, self.contrast / 100.0)
                print(f"Contrast: {self.contrast}")
            elif key == ord('s'):  # Saturation up
                self.saturation = min(100, self.saturation + 5)
                self.cap.set(cv2.CAP_PROP_SATURATION, self.saturation / 100.0)
                print(f"Saturation: {self.saturation}")
            elif key == ord('a'):  # Saturation down
                self.saturation = max(0, self.saturation - 5)
                self.cap.set(cv2.CAP_PROP_SATURATION, self.saturation / 100.0)
                print(f"Saturation: {self.saturation}")
            elif key == ord('r'):  # ROI width increase
                self.roi_width = min(800, self.roi_width + 20)
                print(f"ROI Width: {self.roi_width}")
            elif key == ord('f'):  # ROI width decrease
                self.roi_width = max(100, self.roi_width - 20)
                print(f"ROI Width: {self.roi_width}")
            elif key == ord('t'):  # ROI height increase
                self.roi_height = min(800, self.roi_height + 20)
                print(f"ROI Height: {self.roi_height}")
            elif key == ord('g'):  # ROI height decrease
                self.roi_height = max(100, self.roi_height - 20)
                print(f"ROI Height: {self.roi_height}")
            elif key == 82:  # Up arrow
                self.pan_offset_y -= 10
                print(f"Pan Y: {self.pan_offset_y}")
            elif key == 84:  # Down arrow
                self.pan_offset_y += 10
                print(f"Pan Y: {self.pan_offset_y}")
            elif key == 81:  # Left arrow
                self.pan_offset_x -= 10
                print(f"Pan X: {self.pan_offset_x}")
            elif key == 83:  # Right arrow
                self.pan_offset_x += 10
                print(f"Pan X: {self.pan_offset_x}")
            elif key == ord('e'):  # Export settings
                self.export_settings()
            elif key == ord(' '):  # Spacebar to reset pan
                self.pan_offset_x = 0
                self.pan_offset_y = 0
                print("Pan reset to center")
        
        # Cleanup
        self.cap.release()
        cv2.destroyAllWindows()
        
        # Export final settings automatically
        self.export_settings()
        print("\nFinal settings have been exported to camera_config.py")
        print("\nCopy these values to your actual face detection code:")
        print(f"Zoom factor: {self.zoom_factor}")
        print(f"Pan offset: ({self.pan_offset_x}, {self.pan_offset_y})")
        print(f"Brightness: {self.brightness}")
        print(f"Contrast: {self.contrast}")
        print(f"Saturation: {self.saturation}")
        print(f"Optimal face ROI: {self.roi_width}x{self.roi_height}")


def main():
    # For Raspberry Pi with IMX camera, usually index 0
    # If using USB camera, you might need to try different indices
    adjuster = CameraAdjuster(camera_index=0)
    
    print("=" * 60)
    print("CAMERA ADJUSTMENT TOOL")
    print("=" * 60)
    print("Place the camera in its final position.")
    print("Use the controls to adjust until faces appear in the green rectangle.")
    print("The rectangle shows the optimal face detection area.")
    print("=" * 60)
    
    adjuster.run()


if __name__ == "__main__":
    main()
